import {DownloadIcon} from "@heroicons/react/outline";
import {Link} from "react-router-dom";
import FeaturesSection from "../components/features/features.component";
import OurTeamSection from "../components/our-team/our-team.component";
import ContactUsSection from "../components/contact-us/contact-us.component";
import FooterSection from "../components/footer-section/footer-section.component";

import heroImage from '../assets/undraw_timeline_re_aw6g.svg'
import logo from '../assets/logo.svg'

const LandingPage = () => {
  return (
    <div className="bg-gray-50">
      <header className="text-gray-600 body-font bg-white shadow">
        <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <img src={logo} className="w-12 h-12 p-2" alt="logo" />
            <span className="ml-3 text-xl">
              {import.meta.env.VITE_APP_NAME}
            </span>
          </a>
          <nav className="md:ml-auto md:mr-auto flex flex-wrap items-center text-base justify-center">
            <a className="mr-5 hover:text-gray-900">First Link</a>
            <a className="mr-5 hover:text-gray-900">Second Link</a>
            <a className="mr-5 hover:text-gray-900">Third Link</a>
            <a className="mr-5 hover:text-gray-900">Fourth Link</a>
          </nav>
          <Link
            to="/login"
            className="inline-flex items-center bg-secondary-500 border-0 py-2 px-3 focus:outline-none hover:bg-secondary-600 rounded text-base mt-4 md:mt-0 text-white">
            Login
            <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                 className="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7" />
            </svg>
          </Link>
        </div>
      </header>

      <section className="text-gray-600 body-font min-h-screen">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div
            className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Public Investment
              <br className="hidden lg:inline-block" />Programming System
            </h1>
            <p className="mb-8 leading-relaxed">Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant
              cold-pressed tacos poke beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic
              tumeric truffaut hexagon try-hard chambray.</p>
            <div className="flex justify-center">
              <button
                className="inline-flex text-white bg-secondary-500 border-0 py-2 px-6 focus:outline-none hover:bg-secondary-600 rounded text-lg">
                Get Started
              </button>
              <button
                className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
                Learn More
              </button>
            </div>
          </div>
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
            <img src={heroImage} className="h-full w-full" alt="hero" />
          </div>
        </div>
      </section>

      <section className="text-gray-600 body-font bg-white">
        <div className="container px-5 py-24 mx-auto">
          <div className="text-center mb-20">
            <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900 mb-4">
              Public Investment Program
            </h1>
            <p className="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto text-gray-500s">
              The 2023-2028 Public Investment Program (PIP) contains the rolling list of priority programs and projects (PAPs) to be implemented by the national government (NG), government-owned and controlled corporations (GOCCs), government financial institutions (GFIs), and other national government offices and instrumentalities within the medium term (or the plan period from 2017 to 2022), which respond to the outcomes in the Philippine Development Plan (PDP) and its Results Matrices (RM). These PAPs may be financed using national government funds, including internal cash generated by GOCCs, in partnership with the private sector or through Official Development Assistance (ODA).
            </p>
            <p className="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto text-gray-500s">
              Pursuant to Section 3 of the Executive Order (EO) No. 27 on the implementation of the 2017-2022 Development Plan (PDP) and PIP , and the Special Provision in the General Appropriations Act (GAA) for FY 2018 , NEDA issued on February 7, 2018 a call to agencies for the updating of the 2017-2022 PIP.
            </p>
            <p className="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto text-gray-500s">
              Learn more about the PIP/TRIP updating process with the following reference materials
            </p>
            <div className="flex mt-6 justify-center">
              <div className="w-16 h-1 rounded-full bg-secondary-500 inline-flex"></div>
            </div>
          </div>
          <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">
            <div className="p-4 md:w-1/3 flex flex-col text-center items-center">
              <div
                className="w-20 h-20 inline-flex items-center justify-center rounded-full bg-secondary-100 text-secondary-500 mb-5 flex-shrink-0">
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                     className="w-10 h-10" viewBox="0 0 24 24">
                  <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
                </svg>
              </div>
              <div className="flex-grow">
                <h2 className="text-gray-900 text-lg title-font font-medium mb-3">NEDA Guidelines</h2>
                <p className="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                  taxidermy. Gastropub indxgo juice poutine, ramps microdosing banh mi pug VHS try-hard.</p>
                <a className="mt-3 text-secondary-500 inline-flex items-center">
                  Download
                  <DownloadIcon className="w-4 h-4 ml-2" />
                </a>
              </div>
            </div>
            <div className="p-4 md:w-1/3 flex flex-col text-center items-center">
              <div
                className="w-20 h-20 inline-flex items-center justify-center rounded-full bg-secondary-100 text-secondary-500 mb-5 flex-shrink-0">
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                     className="w-10 h-10" viewBox="0 0 24 24">
                  <circle cx="6" cy="6" r="3"></circle>
                  <circle cx="6" cy="18" r="3"></circle>
                  <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12" />
                </svg>
              </div>
              <div className="flex-grow">
                <h2 className="text-gray-900 text-lg title-font font-medium mb-3">Updated DA Guidelines</h2>
                <p className="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                  taxidermy. Gastropub indxgo juice poutine, ramps microdosing banh mi pug VHS try-hard.</p>
                <a className="mt-3 text-secondary-500 inline-flex items-center">
                  Download
                  <DownloadIcon className="w-4 h-4 ml-2" />
                </a>
              </div>
            </div>
            <div className="p-4 md:w-1/3 flex flex-col text-center items-center">
              <div
                className="w-20 h-20 inline-flex items-center justify-center rounded-full bg-secondary-100 text-secondary-500 mb-5 flex-shrink-0">
                <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                     className="w-10 h-10" viewBox="0 0 24 24">
                  <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2" />
                  <circle cx="12" cy="7" r="4" />
                </svg>
              </div>
              <div className="flex-grow">
                <h2 className="text-gray-900 text-lg title-font font-medium mb-3">Neptune</h2>
                <p className="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                  taxidermy. Gastropub indxgo juice poutine, ramps microdosing banh mi pug VHS try-hard.</p>
                <a className="mt-3 text-secondary-500 inline-flex items-center">
                  Download
                  <DownloadIcon className="w-4 h-4 ml-2" />
                </a>
              </div>
            </div>
          </div>
          <button
            className="flex mx-auto mt-16 text-white bg-secondary-500 border-0 py-2 px-8 focus:outline-none hover:bg-secondary-600 rounded text-lg">
            More
          </button>
        </div>
      </section>

      <FeaturesSection />

      <OurTeamSection />

      <ContactUsSection />

      <FooterSection />
    </div>
  )
}

export default LandingPage