import {DownloadIcon} from "@heroicons/react/outline";

const PipSection = () => {
  return (
    <section className="text-gray-600 body-font bg-white">
      <div className="container px-5 py-24 mx-auto">
        <div className="text-center mb-20">
          <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900 mb-4">
            Public Investment Program
          </h1>
          <p className="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto text-gray-500s">
            The 2023-2028 Public Investment Program (PIP) contains the rolling list of priority programs and projects (PAPs) to be implemented by the national government (NG), government-owned and controlled corporations (GOCCs), government financial institutions (GFIs), and other national government offices and instrumentalities within the medium term (or the plan period from 2017 to 2022), which respond to the outcomes in the Philippine Development Plan (PDP) and its Results Matrices (RM). These PAPs may be financed using national government funds, including internal cash generated by GOCCs, in partnership with the private sector or through Official Development Assistance (ODA).
          </p>
          <p className="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto text-gray-500s">
            Pursuant to Section 3 of the Executive Order (EO) No. 27 on the implementation of the 2017-2022 Development Plan (PDP) and PIP , and the Special Provision in the General Appropriations Act (GAA) for FY 2018 , NEDA issued on February 7, 2018 a call to agencies for the updating of the 2017-2022 PIP.
          </p>
          <p className="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto text-gray-500s">
            Learn more about the PIP/TRIP updating process with the following reference materials
          </p>
          <div className="flex mt-6 justify-center">
            <div className="w-16 h-1 rounded-full bg-secondary-500 inline-flex"/>
          </div>
        </div>
        <div className="flex flex-wrap sm:-m-4 -mx-4 -mb-10 -mt-4 md:space-y-0 space-y-6">
          <div className="p-4 md:w-1/3 flex flex-col text-center items-center">
            <div
              className="w-20 h-20 inline-flex items-center justify-center rounded-full bg-secondary-100 text-secondary-500 mb-5 flex-shrink-0">
              <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                   className="w-10 h-10" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
              </svg>
            </div>
            <div className="flex-grow">
              <h2 className="text-gray-900 text-lg title-font font-medium mb-3">NEDA Guidelines</h2>
              <p className="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                taxidermy. Gastropub indxgo juice poutine, ramps microdosing banh mi pug VHS try-hard.</p>
              <a className="mt-3 text-secondary-500 inline-flex items-center">
                Download
                <DownloadIcon className="w-4 h-4 ml-2" />
              </a>
            </div>
          </div>
          <div className="p-4 md:w-1/3 flex flex-col text-center items-center">
            <div
              className="w-20 h-20 inline-flex items-center justify-center rounded-full bg-secondary-100 text-secondary-500 mb-5 flex-shrink-0">
              <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                   className="w-10 h-10" viewBox="0 0 24 24">
                <circle cx="6" cy="6" r="3"/>
                <circle cx="6" cy="18" r="3"/>
                <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12" />
              </svg>
            </div>
            <div className="flex-grow">
              <h2 className="text-gray-900 text-lg title-font font-medium mb-3">Updated DA Guidelines</h2>
              <p className="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                taxidermy. Gastropub indxgo juice poutine, ramps microdosing banh mi pug VHS try-hard.</p>
              <a className="mt-3 text-secondary-500 inline-flex items-center">
                Download
                <DownloadIcon className="w-4 h-4 ml-2" />
              </a>
            </div>
          </div>
          <div className="p-4 md:w-1/3 flex flex-col text-center items-center">
            <div
              className="w-20 h-20 inline-flex items-center justify-center rounded-full bg-secondary-100 text-secondary-500 mb-5 flex-shrink-0">
              <svg fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                   className="w-10 h-10" viewBox="0 0 24 24">
                <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2" />
                <circle cx="12" cy="7" r="4" />
              </svg>
            </div>
            <div className="flex-grow">
              <h2 className="text-gray-900 text-lg title-font font-medium mb-3">Neptune</h2>
              <p className="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan
                taxidermy. Gastropub indxgo juice poutine, ramps microdosing banh mi pug VHS try-hard.</p>
              <a className="mt-3 text-secondary-500 inline-flex items-center">
                Download
                <DownloadIcon className="w-4 h-4 ml-2" />
              </a>
            </div>
          </div>
        </div>
        <button
          className="flex mx-auto mt-16 text-white bg-secondary-500 border-0 py-2 px-8 focus:outline-none hover:bg-secondary-600 rounded text-lg">
          More
        </button>
      </div>
    </section>
  )
}

export default PipSection
