const DaPipSection = () => {
  return (
    <section className="text-gray-600 body-font">
      <div className="container px-5 py-24 mx-auto">
        <div className="text-center mb-20">
          <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900 mb-4">
            DA Public Investment Program
          </h1>

          <p className="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto text-gray-500s">
            The DA 2023-2028 Public Investment Program (PIP) contains the
            rolling list of priority programs and projects (PAPs) to be
            implemented by the Department of Agriculture, including its attached agencies
            and attached corporations within the medium term (or the plan period from 2023 to 2028),
            which respond to the outcomes in the Philippine Development Plan (PDP) and its Results
            Matrices (RM). These PAPs may be financed  using national government funds, including
            internal cash generated by GOCCs, in partnership with the private sector or through
            Official Development Assistance (ODA).
          </p>

          <p className="text-base leading-relaxed xl:w-3/4 lg:w-3/4 mx-auto text-gray-500s">
            
          </p>

          <div className="flex mt-6 justify-center">
            <div className="w-16 h-1 rounded-full bg-secondary-500 inline-flex"/>
          </div>
        </div>
      </div>
    </section>
  )
}

export default DaPipSection
